- hosts: all
  name: Autoconverted job legacy-bandit-integration-oslo.log from old job gate-bandit-integration-oslo.log
  roles:
    - bindep

  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -u
          set -e
          set -x
          cd $WORKSPACE
          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            git://git.openstack.org \
            openstack/bandit \
            openstack/oslo.log
          cd $WORKSPACE/openstack/bandit
          tox -e integration openstack oslo.log \
            $WORKSPACE/openstack/oslo.log
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
