- hosts: all
  name: Autoconverted job legacy-bandit-integration-oslo.utils from old job gate-bandit-integration-oslo.utils
  roles:
    - bindep

  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -u
          set -e
          set -x
          cd $WORKSPACE
          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            git://git.openstack.org \
            openstack/bandit \
            openstack/oslo.utils
          cd $WORKSPACE/openstack/bandit
          tox -e integration openstack oslo.utils \
            $WORKSPACE/openstack/oslo.utils
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
